ScyllaDB Data Connector: change replication strategy in README example (#504)
>cqlsh> CREATE KEYSPACE IF NOT EXISTS demo
   ... WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
ConfigurationException: SimpleStrategy doesn't support tablet replication